### ISSUE TITLE
你好，请关注有关sib的开源协议问题

### ISSUE THREAD

**Issue by ZhouYixun** [1033866383/app_performance#7]
sib是在AGPL协议下分发的，所以作者你这个项目需要在AGPL协议下进行开源，新建LICENSE文件选择AGPL协议就可以了

https://github.com/SonicCloudOrg/sonic-ios-bridge/blob/main/LICENSE

**Comment by ZhouYixun** [comment]
不是什么大问题，主要是遵循开源环境

**Comment by 1033866383** [comment]
收到！感谢，后续ios能力依赖于sib，这一版做完后我看下这么弄哈，到时候我微信你
